#!/system/bin/sh

#Fix permission issues with gms core "Play Services" in MIUI Marshmallow builds
#PS.: This file can be deleted after the first reboot
#by Dio_S

pm grant com.google.android.gms android.permission.INTERNET
pm grant com.google.android.gms android.permission.USE_CREDENTIALS
pm grant com.google.android.gms android.permission.SYSTEM_ALERT_WINDOW
pm grant com.google.android.gms android.permission.OBSERVE_GRANT_REVOKE_PERMISSIONS
pm grant com.google.android.gms android.permission.INTERACT_ACROSS_USERS
pm grant com.google.android.gms android.permission.READ_PRIVILEGED_PHONE_STATE
pm grant com.google.android.gms android.permission.PACKAGE_USAGE_STATS
pm grant com.google.android.gms android.permission.AUTHENTICATE_ACCOUNTS
pm grant com.google.android.gms android.permission.MANAGE_ACCOUNTS
pm grant com.google.android.gms android.permission.READ_EXTERNAL_STORAGE
pm grant com.google.android.gms android.permission.RECEIVE_BOOT_COMPLETED
pm grant com.google.android.gms android.permission.READ_CALENDAR
pm grant com.google.android.gms android.permission.CAMERA
pm grant com.google.android.gms android.permission.READ_CONTACTS
pm grant com.google.android.gms android.permission.WRITE_EXTERNAL_STORAGE
pm grant com.google.android.gms android.permission.GET_ACCOUNTS
pm grant com.google.android.gms android.permission.ACCESS_FINE_LOCATION
pm grant com.google.android.gms android.permission.ACCESS_COARSE_LOCATION
pm grant com.google.android.gms android.permission.LOCATION_HARDWARE
pm grant com.google.android.gms android.permission.RECORD_AUDIO
pm grant com.google.android.gms android.permission.READ_PHONE_STATE
pm grant com.google.android.gms android.permission.CALL_PHONE
pm grant com.google.android.gms android.permission.READ_CALL_LOG
pm grant com.google.android.gms android.permission.ADD_VOICEMAIL
pm grant com.google.android.gms android.permission.USE_SIP
pm grant com.google.android.gms android.permission.PROCESS_OUTGOING_CALLS
pm grant com.google.android.gms android.permission.BODY_SENSORS
pm grant com.google.android.gms android.permission.SEND_SMS
pm grant com.google.android.gms android.permission.RECEIVE_SMS
pm grant com.google.android.gms android.permission.READ_SMS
pm grant com.google.android.gms android.permission.RECEIVE_WAP_PUSH
pm grant com.google.android.gms android.permission.RECEIVE_MMS
pm grant com.google.android.gms android.permission.READ_CELL_BROADCASTS
